### ISSUE TITLE
[MSKINS-216] Fix issue with missing dependency to plexus-utils in minify-maven-plugin and Maven 3.9.x

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-fluido-skin#272]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** opened **[MSKINS-216](https://issues.apache.org/jira/browse/MSKINS-216?redirect=false)** and commented

```
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (default-minify) on project maven-fluido-skin: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/IOUtil: org.codehaus.plexus.util.IOUtil -> [Help 1]
```

with Maven 3.9.x. Fix for upstream https://github.com/samaxes/minify-maven-plugin/pull/176

---

**Issue Links:**
- [MSKINS-220](https://issues.apache.org/jira/browse/MSKINS-220) cannot build with Maven 3.9
 (_**"is duplicated by"**_)

**Remote Links:**
- [GitHub Pull Request #49
](https://github.com/apache/maven-fluido-skin/pull/49)

**Backported to:** [fluido-1.12.0](https://github.com/apache/maven-fluido-skin/milestone/27?closed=1)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [35d7020a5b56dd3ec11d42694e12c115f0734144](https://gitbox.apache.org/repos/asf?p=maven-fluido-skin.git;a=commit;h=35d7020a5b56dd3ec11d42694e12c115f0734144).

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [cdb20d16cb9491e2685d73ea73db4df6a34f652b](https://gitbox.apache.org/repos/asf?p=maven-fluido-skin.git;a=commit;h=cdb20d16cb9491e2685d73ea73db4df6a34f652b) for 1.x.
