### ISSUE TITLE
[MSKINS-220] cannot build with Maven 3.9

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-fluido-skin#266]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** opened **[MSKINS-220](https://issues.apache.org/jira/browse/MSKINS-220?redirect=false)** and commented

```
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (default-minify) on project maven-fluido-skin: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/IOUtil -> [Help 1]
```

---

**Affects:** fluido-2.0.0-M4

**Issue Links:**
- [MSKINS-216](https://issues.apache.org/jira/browse/MSKINS-216) Fix issue with missing dependency to plexus-utils in minify-maven-plugin and Maven 3.9.x
 (_**"duplicates"**_)
- [MNG-6965](https://issues.apache.org/jira/browse/MNG-6965) Extensions suddenly have org.codehaus.plexus:plexus-utils:jar:1.1 on their classpath
 (_**"is caused by"**_)
